### ISSUE TITLE
Unable to shutdown fastcraftplus on stop server

### ISSUE THREAD

**Issue by Sodies** [BenWoodworth/FastCraft#122] opened 2017-12-11 19:44 UTC
## Description
I wanna report that the fastcraft plugs plugin has a problem
which idk what it is.

I have been checking the config and I don't think the config caused any errors

But the error was when i /stop my server the FastCraftPlus plugin took
a long time to successfully disabled or sometimes it won't disable and it stuck at 

[16:10:42 INFO]: [FastCraft+] Disabling FastCraftPlus v0.27.2

## Reproduction
- On server stop
- The plugin doesn't disabled
- Stucked

## Server Details
- v0.27.2
- spigot-1.12.2-R0.1-SNAPSHOT-b1461
- Tried just FastCraftPlus plugin only but still doesn't works

**Comment by Cri16228** [comment] 2018-03-23 20:15
*Follow*
Same problem

**Comment by BenWoodworth** [comment] 2018-03-23 20:30
Give this a try:
http://s3.amazonaws.com/fastcraft/circleci/105/FastCraft-2.x-18919b2.jar

It's worked for other people who had the same problem.

**Comment by BenWoodworth** [comment] 2018-03-23 20:31
Duplicate of #133

**Closed by BenWoodworth** 2018-03-23 20:31 UTC
Labels: duplicate

**Comment by HSJGITHUB** [comment] 2020-02-24 10:18
> Give this a try:
> http://s3.amazonaws.com/fastcraft/circleci/105/FastCraft-2.x-18919b2.jar
> 
> It's worked for other people who had the same problem.

I've come across this issue since my server has been experiencing the exact same problem as these multiple issues (duplicate of #133).
![linkerror](https://user-images.githubusercontent.com/61411429/75144158-c3537380-5739-11ea-82cf-d0b0fdcf18c7.PNG)
I really want to try out the temporary fix version, but it seems like the download link broken. Could you please update the link?

**Comment by BenWoodworth** [comment] 2020-02-24 15:05
> > Give this a try:
> > http://s3.amazonaws.com/fastcraft/circleci/105/FastCraft-2.x-18919b2.jar
> > It's worked for other people who had the same problem.
> 
> First of all, I'm sorry for commenting on a closed issue. I've come across this issue since my server has been experiencing the exact same problem as these multiple issues (duplicate of #133).
> ![linkerror](https://user-images.githubusercontent.com/61411429/75144158-c3537380-5739-11ea-82cf-d0b0fdcf18c7.PNG)
> I really want to try out the temporary fix version, but it seems like the download link broken. Could you please update the link?

No worries! I'll post a build in a bit when I'm home. In the meantime, could you try a v3.0-alpha build to see if it solves the problem? You can find it on this project's releases page

**Comment by BenWoodworth** [comment] 2020-02-25 05:55
Here you go! I still recommend the v3.0 alpha build if it works, though.
[FastCraft-2.x-18919b2.zip](https://github.com/BenWoodworth/FastCraft/files/4248276/FastCraft-2.x-18919b2.zip)

**Comment by HSJGITHUB** [comment] 2020-02-25 09:45
Wow, great thanks for the quick reply!

Regarding your recommendation, I've tried all of the v3.0 alpha builds before leaving a comment on this thread, but it just didn't work on my server. I'm not sure if it's because of complex permission settings or a custom language translation, but I simply couldn't get it running in my server's full configuration. For your information, my server's running on git-Paper-1617 (MC:1.12.2), 1.12.2-R0.1-SNAPSHOT.

Anyway, that 2.x-18919b2 build worked like a charm! The server doesn't have any issues stopping and restarting now. It's such a lifesaver. Again, thank you for creating such an amazing plugin!

**Comment by BenWoodworth** [comment] 2020-02-27 03:50
I just released ([here](https://github.com/BenWoodworth/FastCraft/releases)), which adds support for Bukkit 1.8+, so it should be able to run on your server. Could you give it a try?
