### ISSUE TITLE
No crafting drop and server freeze (semi freeze) 

### ISSUE THREAD

**Issue by Cri16228** [BenWoodworth/FastCraft#137] opened 2018-03-23 20:24 UTC
## Description
When I use the fastcraft plugin and I break the crafting no issues but when I play with friends and I break the crafting it doesn't drop anything and I have problems with my inventory, if I open my inventory it close immediately.
If I disable the plugin with plugman (or I remove it) I dont have this issue

## Reproduction
- Play with friends
- Break the crafting
- No crafting drop

## Server Details
- FastCraft Version: 2.0.2 and 2.0.3
- Server Version: SPIGOT 1.12
- RELEVANT PLUGINS: I don't know what it means. If It means all the plugins I can send you the list

**Comment by BenWoodworth** [comment] 2018-03-23 20:36
Thanks for reporting!
Is this correct?
-FastCraft is open
-Another player breaks the crafting table block
-Items don't drop from the crafting table

And what items aren't being dropped that should be?

**Comment by Cri16228** [comment] 2018-03-23 20:45
I don't know if this happen but If I place and break my crafting (after a use) it doesnt drop

**Comment by BenWoodworth** [comment] 2018-03-23 20:48
So after you close Fast craft, and break the crafting table, a crafting table item isn't dropped?

**Comment by Cri16228** [comment] 2018-03-23 21:01
Yes and If I open creative/survival inventories it is closed automatically

**Comment by BenWoodworth** [comment] 2018-03-24 18:07
I'm not able to reproduce this with either of these tests.

Test 1:
- Place workbench
- Break workbench
- Workbench item is dropped (as expected)

Test 2:
- Place workbench
- Right click to open FastCraft
- Craft items
- Break workbench
- Workbench item is dropped (as expected)

And after these, I'm still able to open other inventories. Could you see if you have the issue on a server with only FastCraft? It's possible there's a conflict with another plugin. Otherwise, I'm not sure what's going on.

**Comment by Cri16228** [comment] 2018-03-24 18:24
I've tried with your plugin, my custom commandcore (come essentials commands) and my plugin that adds custom crafting taken from yml
Maybe the problem is that? The custom recipes?

**Comment by BenWoodworth** [comment] 2018-03-28 13:20
Hmm... I'm not sure. Do you think you could record a video of the bug, or maybe share step-by-step what's happening (down to each mouse click)?

I don't think there's any code in FastCraft that prevents inventories from opening like that, so it's tough figuring out what's happening.

**Comment by Cri16228** [comment] 2018-03-28 13:46
Hmmm.. Now I don't have this bug, I don't know why, if it's happening again I'll send you a video.
Now the problem is if I shutdown the server, sometimes it stuck at "Disabling FastCraft 2.0.x"

**Comment by BenWoodworth** [comment] 2018-03-28 15:10
Interesting. I'm going to close this issue for now, and I'll re-open it if you get any other information.

For the shutdown issue, could you share some info, like what plugins are on the server, in this issue?
https://github.com/BenWoodworth/FastCraft/issues/133

**Closed by BenWoodworth** 2018-03-28 15:10 UTC
