### ISSUE TITLE
Incompatiblity with QuestCreator

### ISSUE THREAD

**Issue by WarnDangerous** [BenWoodworth/FastCraft#191] opened 2021-05-31 18:32 UTC
## Description
The fastcraft doesn't work with QuestCreator. In this plugin I got a quest where player need to craft 1000 amount of an item, but when he uses fastcraft to craft 64x the item, it counts only one in the quest.

## Server Details
- Server: 
- FastCraft: v3.2.9
- QuestCreator 6.20.0 https://www.spigotmc.org/resources/questcreator-new-configuration-presets.38734/

**Comment by BenWoodworth** [comment] 2021-05-31 20:03
FastCraft's multiplier pretends to craft with shift-clicking the result slot. When you craft normally with 64 of each ingredient, does shift-clicking count 64 times in the quest?

**Comment by WarnDangerous** [comment] 2021-05-31 20:06
This item is "special" and can only be craft 1 by 1, (it's beetroot soup), that's maybe why it has some issues.

But I don't know how to fix it

**Comment by BenWoodworth** [comment] 2021-05-31 20:08
Oh I see. Can you show me how to setup the plugin (or zip QuestCreator's plugin folder) and how to craft the item?

**Comment by WarnDangerous** [comment] 2021-05-31 20:12
For questcreator it's a basic thing like : 
`        type: PLAYER_ITEMS_CRAFT
        items:
          a:
            item:
              type: BEETROOT_SOUP
            goal: 1024.0`

but this won't change things,
and to craft the beetroot soup, I set all the item and fastcraft craft them, I don't know how I can help you on this :/

The plugin just basically caught the crafting event, so you maybe have to "simulate" that the player craft the item 64 times instead of one

**Comment by WarnDangerous** [comment] 2021-06-09 14:50
Hello,

Any news ? :)

**Comment by BenWoodworth** [comment] 2021-06-09 15:59
Oh hey, sorry! I just sent an email to the QuestCreator dev about getting access to the plugin. From there I'll see what's causing the problem and share the details here :)

**Comment by BenWoodworth** [comment] 2021-06-10 15:33
He was actually pretty quick to respond!

I have a test server setup but I'm not sure how to setup/start a (crafting) quest. (I looked through the documentation briefly)

Could you share how to start this quest? (what commands I need to run, or what I need to configure)
I'm not sure where the `type: PLAYER_ITEMS_CRAFT ...` goes.

I just don't want to spend a lot of time researching and figuring this out

![image](https://user-images.githubusercontent.com/1829157/121553875-afd82480-c9df-11eb-9521-5b13b24872e7.png)

**Comment by WarnDangerous** [comment] 2021-06-10 15:52
Add me on discord :
WarnD#0001

It will be easier :)

**Comment by BenWoodworth** [comment] 2021-06-10 17:17
Closing since it seems to be an issue with Quest Creator.
Dropped items don't count towards the quest (e.g. vanilla crafting grid: crafting with Q)

Reproduction:

Put in `plugins/QuestCreator/quest_models/`:
[soup.zip](https://github.com/BenWoodworth/FastCraft/files/6633233/soup.zip)

Reload, then:
`/qc start soup`

**Closed by BenWoodworth** 2021-06-10 17:17 UTC
